server.port=8080
server.address=0.0.0.0

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (AIVEN CLOUD)
# ==========================================
spring.datasource.url=jdbc:mysql://mysql-ab38c59-sys02project.c.aivencloud.com:16259/ss_inventorydb?sslMode=REQUIRED
spring.datasource.username=avnadmin
# Cambia la línea de la contraseña de Aiven por esto:
spring.datasource.password=${DB_PASSWORD}

# Cambia la línea de la contraseña de Gmail por esto:

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACIÓN DE SERVIDOR DE CORREOS (GMAIL)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sebastiantriana.0223@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true